stages:
  - lint

.js_cache: &js_cache
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

check formatting for pr:
  stage: lint
  before_script:
    - apk add git
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install --frozen-lockfile
    - git fetch origin "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
    - DIFFED_FILES_TO_LINT=$(git diff --diff-filter=d --name-only "origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}" "${CI_COMMIT_SHA}" | { grep "^src/.*\.\(js\|ts\|jsx\|tsx\|css\|scss\|html\|md\)$" || true; } | tr '\n' ' ' | sed 's/ *$//')
    - echo "${DIFFED_FILES_TO_LINT}" | tr ' ' '\n'
    - if [ ! -z "${DIFFED_FILES_TO_LINT}" ]; then npx prettier --check ${DIFFED_FILES_TO_LINT}; fi
  timeout: 10 minutes
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - src/**/*.{js,ts,jsx,tsx,css,scss,html,md}

check eslint for pr:
  stage: lint
  before_script:
    - apk add git
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install --frozen-lockfile
    - git fetch origin "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
    - DIFFED_FILES_TO_LINT=$(git diff --diff-filter=d --name-only "origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}" "${CI_COMMIT_SHA}" | { grep "^src/.*\.\(ts\|tsx\|js\|jsx\)$" || true; } | tr '\n' ' ' | sed 's/ *$//')
    - echo "${DIFFED_FILES_TO_LINT}" | tr ' ' '\n'
    - if [ ! -z "${DIFFED_FILES_TO_LINT}" ]; then npx eslint -c ./.eslintrc-ci.json ${DIFFED_FILES_TO_LINT}; fi
  timeout: 10 minutes
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - src/**/*.{js,ts,jsx,tsx}

check stylelint for pr:
  stage: lint
  before_script:
    - apk add git
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install --frozen-lockfile
    - git fetch origin "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
    - DIFFED_FILES_TO_LINT=$(git diff --diff-filter=d --name-only "origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}" "${CI_COMMIT_SHA}" | { grep "^src/.*\.\(css\|scss\)$" || true; } | tr '\n' ' ' | sed 's/ *$//')
    - echo "${DIFFED_FILES_TO_LINT}" | tr ' ' '\n'
  timeout: 10 minutes
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - src/**/*.{css,scss}
